FROM openjdk:17-jdk

COPY gateway/build/libs/indistraw-gateway-0.0.1-SNAPSHOT.jar gateway/build/libs/indistraw-gateway-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java","-jar","gateway/build/libs/indistraw-gateway-0.0.1-SNAPSHOT.jar"]