spring:
  cloud:
    gateway:
      routes:
        - id: indistraw-account-route
          uri: ${ACCOUNT_ROUTE_URI}
          predicates:
            - Path=/api/v1/account/**
          filters:
            - JwtAuthenticationGatewayFilter

        - id: indistraw-file-route
          uri: ${FILE_ROUTE_URI}
          predicates:
            - Path=/api/v1/file/**

        - id: indistraw-auth-route
          uri: ${AUTH_ROUTE_URI}
          predicates:
            - Path=/api/v1/auth/**

jwt:
  accessSecret: ${JWT_ACCESS_SECRET}