package com.project.indistraw.crowdfunding.application.exception

import com.project.indistraw.crowdfunding.application.common.error.ErrorCode
import com.project.indistraw.crowdfunding.application.common.error.exception.IndiStrawCrowdfundingException

class RewardNotFoundException: IndiStrawCrowdfundingException(ErrorCode.REWARD_NOT_FOUND)