FROM openjdk:17-jdk

COPY crowdfunding/build/libs/indistraw-crowdfunding-0.0.1-SNAPSHOT.jar crowdfunding/build/libs/indistraw-crowdfunding-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java","-jar","crowdfunding/build/libs/indistraw-crowdfunding-0.0.1-SNAPSHOT.jar"]