spring:
  cloud:
    gateway:
      routes:
        - id: indistraw-account-route
          uri: ${ACCOUNT_ROUTE_URI}
          predicates:
            - Path=/api/v1/account/**
          filters:
            - JwtAuthenticationGatewayFilter

        - id: indistraw-file-route
          uri: ${FILE_ROUTE_URI}
          predicates:
            - Path=/api/v1/file/**

        - id: indistraw-auth-route
          uri: ${AUTH_ROUTE_URI}
          predicates:
            - Path=/api/v1/auth/**

        - id: indistraw-qr-code-route
          uri: ${AUTH_ROUTE_URI}
          predicates:
            - Path=/api/v1/qr-code/**

        - id: indistraw-qr-code-route
          uri: ${AUTH_ROUTE_URI}
          predicates:
            - Path=/api/v1/qr-code/signin
          filters:
            - JwtAuthenticationGatewayFilter

        - id: indistraw-crowdfunding-route
          uri: ${CROWDFUNDING_ROUTE_URI}
          predicates:
            - Path=/api/v1/crowdfunding/**
          filters:
            - JwtAuthenticationGatewayFilter

        - id: indistraw-search-route
          uri: ${SEARCH_ROUTE_URI}
          predicates:
            - Path=/api/v1/search/**
          filters:
            - JwtAuthenticationGatewayFilter

  security:
    enable-csrf: false

jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
