# Generated by Django 4.2.3 on 2023-07-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRecommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('movie_id', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=100)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandation.viewrecord')),
            ],
        ),
    ]
