# Generated by Django 4.2.3 on 2023-07-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genredata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recommandation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='viewrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='genredata',
            name='genre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='genredata',
            name='movie_id',
            field=models.CharField(max_length=9999, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommandation.viewrecord'),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='record',
            field=models.CharField(max_length=2990),
        ),
        migrations.AlterField(
            model_name='viewrecord',
            name='account_id',
            field=models.CharField(max_length=9999, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='viewrecord',
            name='record',
            field=models.CharField(max_length=9990),
        ),
    ]
