# Generated by Django 4.2.3 on 2023-07-10 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0002_remove_genredata_id_remove_recommandation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genredata',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='record',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None),
        ),
        migrations.AlterField(
            model_name='viewrecord',
            name='record',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None),
        ),
    ]
