# Generated by Django 4.2.3 on 2023-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0003_alter_genredata_genre_alter_recommandation_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genredata',
            name='image_url',
            field=models.URLField(default='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png', max_length=9999),
        ),
    ]
