# Generated by Django 4.2.3 on 2023-07-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0004_genredata_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genredata',
            old_name='image_url',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='genredata',
            old_name='movie_id',
            new_name='movie_idx',
        ),
        migrations.RenameField(
            model_name='recommandation',
            old_name='account_id',
            new_name='account_idx',
        ),
        migrations.RenameField(
            model_name='viewrecord',
            old_name='account_id',
            new_name='account_idx',
        ),
    ]
