# Generated by Django 4.2.3 on 2023-07-14 00:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0006_delete_defaultrecommandation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genredata',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
    ]
