# Generated by Django 4.2.1 on 2023-06-30 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_idx', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField()),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField()),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('movie_url', models.URLField(default='')),
                ('thumbnail_url', models.URLField(default='')),
                ('genre', models.JSONField(default='{}')),
                ('movie_highlight', models.JSONField(default='{}')),
                ('account_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.account')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.director')),
            ],
        ),
        migrations.CreateModel(
            name='MovieHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('history_time', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('account_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('movie_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
            ],
        ),
    ]
