# Generated by Django 4.2.1 on 2023-07-13 05:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_idx', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('profile_url', models.URLField()),
                ('name', models.CharField(max_length=24)),
                ('movie_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('profile_url', models.URLField()),
                ('name', models.CharField(max_length=24)),
                ('movie_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('movie_url', models.URLField(default='', max_length=2000)),
                ('thumbnail_url', models.URLField(default='', max_length=2000)),
                ('director', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('actor', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('movie_highlight', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('clowd_true', models.BooleanField(default=False)),
                ('movie_idx', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MovieHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('history_time', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('account_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('movie_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
            ],
        ),
    ]
