# Generated by Django 4.2.1 on 2023-07-13 06:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_actor_movie_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movie_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='director',
            name='movie_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], null=True, size=None),
        ),
    ]
