name: Django Movie CD

on:
  push:
    branches: [ "Django" ]
    paths:
      - "AI/**"  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd ./AI
        pip install -r requirements.txt
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name : Create .env
      run: |
        touch ./AI/.env
        echo "${{ secrets.AI_DJANGO_ENV }}" > ./AI/.env
        
    - name: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "./AI/indiestraw.json"
        json: ${{ secrets.INDIESTRAW_JSON }}
      
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        cd AI
        docker build -t ${{ secrets.AI_ECR_REPOSITORY }} .
        docker tag ${{ secrets.AI_ECR_REPOSITORY }}:$IMAGE_TAG ${{ secrets.AI_REPO_URL }}:$IMAGE_TAG
        docker push ${{ secrets.AI_REPO_URL }}:$IMAGE_TAG
          
    - name: CD Discord Django Success Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: ✅ Django AI CD success ✅
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        color: 00FF00
        
    - name: CD Discord Django Success Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: ❗️  Django AI CD failed ❗️
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        color: FF0000
