name: Spring-Account CI

on:
  push:
    branches: [ "main", "Spring" ]
  pull_request:
    branches: [ "Spring", "Spring-Account" ]
    
permissions:
  contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./account
    steps:
    - name : Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up JDK 11 job success
      if: ${{success()}}
      run: echo "JDK 11 job succeeded"
      
    - name: Setup Gradle's permission
      run : chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Gradle clean and Build  
      run: ./gradlew clean build
      working-directory: ${{ env.working-directory }}
      
    - name: Spring-Account CI Success Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: ✅ Spring-Account CI success ✅
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        color: 00FF00
    
    - name: Spring-Account CI Failed Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: ❗️ Spring-Account CI failed ❗️
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        color: FF0000
      
